### ISSUE TITLE
Can script run without sudo?

### ISSUE THREAD

**Issue by ghost** [ripeda/macOS-Pkg-Builder#1]
Is it possible not to run script with sudo. Also i have selected path for installation but for git clone i need to write path. Can you please make an update for it. Thanks

**Comment by khronokernel** [comment]
Hello,

Sorry for the late reply, to answer: Apple's Package format runs scripts as root when the pkg has non-user home directories involved (ie. anything not in `~/`).

To work around this, you will need to add the following function to your scripts, and call the function as needed:
```zsh
_runAsUser() {
	currentUser=$( echo "show State:/Users/ConsoleUser" | /usr/sbin/scutil | /usr/bin/awk '/Name :/ { print $3 }' )
	uid=$(/usr/bin/id -u "${currentUser}")
	if [[ "${currentUser}" != "loginwindow" ]]; then
		/bin/launchctl asuser "$uid" sudo -u "${currentUser}" "$@"
	else
		echo "No user logged in, exiting..."
		exit 1
	fi
}
```

```zsh
# Example invocation
_runAsUser /usr/bin/defaults write com.apple.finder ShowPathbar -bool true
```

* Reference: [Running a Command as another User](https://scriptingosx.com/2020/08/running-a-command-as-another-user/)

**Comment by ghost** [comment]
Thank you

**Comment by ghost** [comment]
But is it possible to add this to python something like run_as_user your-script.sh thanks

**Comment by khronokernel** [comment]
> But is it possible to add this to python something like run_as_user your-script.sh thanks

Due to how packages work (simply running pre/postinstall scripts as-is), the library would therefore need to wrap your scripts to "run as user". This adds both additional complexities as well as potential issues/incompatibilities when mixing scripts that don't understand each other (ex. wrapping bash script in zsh, etc).

This is where the library's `pkg_script_resources` parameter would be useful. You can bundle your own additional scripts in then, instead of relying on a hard coded script in this library:
```python
Packages(
    ...
    pkg_script_resources=[
        "run_as_user.sh",
    ],
)
```

Then you could invoke the `run_as_user.sh` inside your pre/postinstall scripts:
```
./run_as_user.sh /usr/bin/defaults write com.apple.finder ShowPathbar -bool true
```

------

A sample of this kind of package is available below, `Sample-Wallpaper.pkg` (utilizing `desktoppr`, a wallpaper utility that is only invoked by the pre/postinstall script but not installed into any directories):
* https://github.com/ripeda/macOS-Pkg-Builder/blob/2.0.2/Samples/validation.py#L38-L49
* https://github.com/ripeda/macOS-Pkg-Builder/tree/2.0.2/Samples/MyWallpaperConfigurator

```python
Packages(
    pkg_output="Sample-Wallpaper.pkg",
    pkg_bundle_id="com.myapp.wallpaper",
    pkg_file_structure={
        "Samples/MyWallpaperConfigurator/Snow Leopard Server.jpg": "/Library/Desktop Pictures/Snow Leopard Server.jpg",
    },
    pkg_preinstall_script="Samples/MyWallpaperConfigurator/PrepareDirectory.sh",
    pkg_postinstall_script="Samples/MyWallpaperConfigurator/SetWallpaper.sh",
    pkg_script_resources=[
        "Samples/MyWallpaperConfigurator/desktoppr",
    ],
)
```
```sh
# postinstall script
./desktoppr "/Library/Desktop Pictures/Snow Leopard Server.jpg"
```
